### ISSUE TITLE
Pass Win32 Window Handle to ShowDialog()

### ISSUE THREAD

**Issue by mu88** [augustoproiete/ookii-dialogs-wpf#18]
I'd like to pass a Win32 Window Handle (e. g. from Microsoft Word, Excel or Outlook) into `TaskDialog.ShowDialog()`. For this, it seems to be sufficient to make `TaskDialog.ShowDialog(IntPtr owner)` `public` instead of `private`.

What do you think about making this method `public`? I could provide a PR if you want.

Thanks!

**Comment by augustoproiete** [comment]
Hi @mu88, in principle I'm OK with that change if there are scenarios where `GetActiveWindow` returns the handle to an incorrect window `IntPtr` - is that the case?

Are using the TaskDialog from within an Excel add-in or similar?

If so, does passing a `null` to `Task.ShowDialog(Window)` get wrong owner handle?

**Comment by mu88** [comment]
Thanks for getting back so quickly, @augustoproiete !

We're developing a WPF application. This application communicates with Excel via COM and retrieves Excel's window handle as `IntPtr` via [`Process.MainWindowHandle`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.mainwindowhandle?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(System.Diagnostics.Process.MainWindowHandle);k(DevLang-csharp)%26rd%3Dtrue&view=netcore-3.1). Now we want to show a custom `TaskDialog` within Excel - so the dialog's owner has to be Excel's window handle. So in our case, there is no WPF window that can act as owner since Excel is not based on WPF.

I gave it a try by calling `private TaskDialogButton ShowDialog(IntPtr owner)` via reflection and it works like a charme.

**Comment by mu88** [comment]
Yes I'll go for this PR

**Comment by augustoproiete** [comment]
Closed via #19

**Comment by mu88** [comment]
Can you please create a new version for NuGet, @augustoproiete ?

**Comment by augustoproiete** [comment]
Sure @mu88. I'll push a new vesion to nuget.org by tomorrow evening

**Comment by augustoproiete** [comment]
@mu88 NuGet package published to nuget.org - https://www.nuget.org/packages/Ookii.Dialogs.Wpf/1.2.0

**Comment by mu88** [comment]
Thank you @augustoproiete ! I've integrated the new package and it works like a charm 🥳
