### ISSUE TITLE
Publish nuget package that contains .NET Core 3.1 assemblies

### ISSUE THREAD

**Issue by Insire** [augustoproiete/ookii-dialogs-wpf#20]
Hi,

i noticed that you merged and pushed support for .NET Core 3.1 here on github. It would be great, if the official nuget package would reflect that support aswell. Right now, there are only .NET 4.5 assemblies in there. Which causes a warning when restoring and building a project with that version.

Your package on [fuget](https://www.fuget.org/packages/Ookii.Dialogs.Wpf).

What i get when i download the package manually:
![grafik](https://user-images.githubusercontent.com/11455827/98227414-99548100-1f57-11eb-9c03-92cf6a1cbba8.png)

Then warning in question:

```3>E:\Code\Maple\src\Maple\Maple.csproj : warning NU1701: Package 'Ookii.Dialogs.Wpf 1.2.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.```

My project targets ``<TargetFrameworks>netcoreapp3.1</TargetFrameworks>``

**Comment by augustoproiete** [comment]
Hey @Insire, yes I did all those things you mentioned, last night, but just in a different order... I released Ookii.Dialogs v1.2.0 **first**, from the [master](https://github.com/augustoproiete/ookii-dialogs-wpf/tree/master) branch which [contains a number of features](https://github.com/augustoproiete/ookii-dialogs-wpf/releases/tag/v1.2.0) that made in before the .NET Core 3.1 merge into the [develop](https://github.com/augustoproiete/ookii-dialogs-wpf/tree/develop) branch which is still a work-in-progress.

Support for .NET Core 3.1 will come in a few days as **version 2.0.0** and I'll release at least one pre-release package (#5) before the final 2.0.0 release, probably over the weekend.

**Comment by Insire** [comment]
i'll be patient then. :)

**Comment by augustoproiete** [comment]
@Insire, the [**Ookii.Dialogs.Wpf 2.0.0-preview1**](https://www.nuget.org/packages/Ookii.Dialogs.Wpf/2.0.0-preview1) has been published on nuget.org

```powershell
Install-Package Ookii.Dialogs.Wpf -Version 2.0.0-preview1
```

Please test in your apps and report any issues you find.

---

Thanks to @acemod13 for doing all the work!

**Comment by Insire** [comment]
Hi,

thx for the update. With the new preview version the warning is gone and the ``VistaOpenFileDialog`` seems to be working as expected. Thx!

**Comment by augustoproiete** [comment]
@Insire, the stable version with .NET 3.1 support has been published to nuget.org: [**Ookii.Dialogs.Wpf 2.0.0**](https://www.nuget.org/packages/Ookii.Dialogs.Wpf/2.0.0)

```powershell
Install-Package Ookii.Dialogs.Wpf -Version 2.0.0
```

N.B.: WPF apps on .NET Core 3.1 need to declare an application manifest in order to use Ookii Dialogs. The manifest was added automatically in .NET Framework apps, but with .NET Core 3.1 this is no longer the case, so there's a little extra step that the developer needs to do. More details on the [README](https://github.com/augustoproiete/ookii-dialogs-wpf#net-core-31-pre-requisites) of this repo.

---

Thanks again to @acemod13 for the contribution!

**Comment by Insire** [comment]
I'll keep that in mind. Thanks for the update and your work.
